import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import '../../../fontify.css'
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Generamos los parámetros estáticos para las rutas
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {
  // Validamos que el locale sea válido
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Obtenemos los mensajes para el locale específico
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="antialiased text-white bg-black">
        <NextIntlClientProvider 
          locale={locale} 
          messages={messages}
          timeZone="America/Los_Angeles"
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}